### ISSUE TITLE
GUI Issues for PX4 Sim on Mac and Windows

### ISSUE THREAD

**Issue by tabaddor** [MAAV-Software/mission9-2021#3]
Mac and Window users are still unable to view the GUI for the Gazebo simulator. 

I believe it is most likely due to an incorrect setting of a display error. Minor issue, but important to resolve so all members across all OS's can test while seeing the sim.

**Comment by jaminock** [comment]
Just now seeing this formal issue about the Windows/Mac GUIs. The necessary config changes should be merged in to fix these issues. However, there may be more issues with available first-time setup documentation...

I will look into refining the first-time setup docs for Windows (since that's the only OS I have access to).
